### PR TITLE
fix Aqua test

### PR DESCRIPTION
**Pull request by ogauthe**
This PR mimics https://github.com/ITensor/FusionTensors.jl/pull/3:
- remove test/Project.toml
- enable Aqua test
- not sure of this: remove sources from `Project.toml`. This was needed to get passing tests.

With this PR, `] test SymmetrySectors` passes all test in the local project.

### CODE REVIEW

**Comment by ogauthe** [comment]
Hmm, looks like I missed something. @lkdvos do you have a clue?

**Comment by lkdvos** [comment]
I'll have a look later, but it seems like we're both doing the same thing: https://github.com/ITensor/SymmetrySectors.jl/pull/3

**Comment by ogauthe** [comment]
Indeed, I wrote this PR to fix tests in #4 but #3 may already fix them. I will close this if #4 test pass once #3 is merged.

**Comment by lkdvos** [comment]
Sorry, I was reading this on my phone this morning and didn't really see what was going on. Indeed, the problems should be fixed with the changes in that other PR.

In case you wanted to know in more detail, the issue here is that this version of the CI test script is not yet using the centralized one we have in `ITensors/ITensorActions`. The main difference is that the `buildpkg` substep takes an (optional) argument to supply additional registries that you want it to install, which here is required for the CI to find the `LabelledNumbers.jl` package. The relevant line is:
https://github.com/ogauthe/SymmetrySectors.jl/blob/b501810d74bcb1646763fe55b63f5ab67120fab8/.github/workflows/CI.yml#L41
compared to
https://github.com/ITensor/ITensorActions/blob/617bb0004c5a4704e6db4f6372e07f37a79f57d8/.github/workflows/Tests.yml#L103-L106

**Comment by ogauthe** [comment]
No more needed thanks to #3

**Pull request closed without merging**
